version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./infrastructure/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - php-fpm
    volumes:
      - ./backend/:/var/www/html

  php-fpm:
    build:
      context: .
      dockerfile: ./infrastructure/php-fpm/Dockerfile
    volumes:
      - ./backend/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  mysql:
    build:
      context: .
      dockerfile: ./infrastructure/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
